#!/usr/bin/env python3
"""Regenerates src/levels/garden-data.js from research/03-progression.md section 2.11 (the unlock table)."""
import re, json, os
os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
rows = []
for ln in open("research/03-progression.md"):
    m = re.match(r"\| (\d+) \| (L\d\.\d\d) \| (.*?) \| (.*?) \| (plant|path|landmark) \|", ln)
    if m: rows.append((m.group(2), re.sub(r"\s*\(.*\)$", "", m.group(4).strip()), m.group(5)))
assert len(rows) == 108
T = {"plant": "p", "path": "r", "landmark": "l"}
Z = {n: [[i, nm, "t" if n == 7 and t == "plant" else T[t]] for i, nm, t in rows if int(i[1]) == n] for n in range(1, 8)}
meta = {1: ("Seed Garden", "flowers", ["#E8C23D", "#E27D9B", "#7AB3E8", "#B58AD8"], "Garden Gate"),
 2: ("Pond Meadow", "reeds", ["#6FB7A6", "#A9C96A", "#E8A75A", "#8FB8E0"], "Stone Pond"),
 3: ("Whispering Wood", "woodland", ["#5E9D5A", "#C9833E", "#7C9D3C", "#D8B25A"], "Wooden Bridge"),
 4: ("Lantern Grove", "grove", ["#4F8F6A", "#B55A4A", "#D9A441", "#7F6BB0"], "Lantern"),
 5: ("Windmill Orchard", "orchard", ["#D95F4B", "#E8A33D", "#8BB84A", "#C46A9B"], "Windmill"),
 6: ("Banyan Commons", "wetland and fields", ["#3F9C8F", "#D8B04A", "#6AA84F", "#B9785A"], "Great Banyan Courtyard"),
 7: ("Tool Shed Hill", "tools", ["#8A8372", "#B9894A", "#5E7FA6", "#7A9A5E"], "Observatory")}
js = "// Generated by tools/make_garden_data.py from research/03-progression.md 2.11 (108 lessons: 85 plants, 13 shed tools, 3 path pieces, 7 landmarks).\n// item type: p plant, t shed tool (Level 7), r path, l landmark.\n"
js += "export const ZONES = " + json.dumps([dict(n=n, name=meta[n][0], family=meta[n][1], palette=meta[n][2], landmark=meta[n][3], items=Z[n]) for n in range(1, 8)], ensure_ascii=False, separators=(",", ":")) + ";\n"
open("src/levels/garden-data.js", "w").write(js)
print("garden-data.js:", {n: len(v) for n, v in Z.items()})
